name: Qt5 Build and Release

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build:
    strategy:
      fail-fast: false  # 不要因为一个平台失败就停止其他平台
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        qt-version: ['5.15.2']
        
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Qt (Windows/Linux)
      if: matrix.os != 'macos-latest'
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ matrix.qt-version }}
        modules: 'qtnetworkauth'
        
    - name: Install Qt (macOS)
      if: matrix.os == 'macos-latest'
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ matrix.qt-version }}
        arch: 'clang_64'
        target: 'desktop'
        # macOS Qt 5.15.2 doesn't need separate modules, core components are included
        
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build libboost-all-dev
        
    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install ninja
        # Install vcpkg and full boost library
        git clone https://github.com/Microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
        # Install the full boost package which includes asio
        .\vcpkg\vcpkg.exe install boost:x64-windows
        
    - name: Debug Boost installation (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        echo "Checking Boost installation..."
        dir vcpkg\installed\x64-windows\include\boost
        if (Test-Path "vcpkg\installed\x64-windows\include\boost\asio.hpp") {
          echo "boost/asio.hpp found!"
        } else {
          echo "boost/asio.hpp NOT found!"
        }
        dir vcpkg\installed\x64-windows\lib
        
    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install ninja boost
        
    - name: Setup MSVC (Windows)
      if: matrix.os == 'windows-latest'
      uses: ilammy/msvc-dev-cmd@v1
      
    - name: Configure CMake (Windows)
      if: matrix.os == 'windows-latest'
      continue-on-error: true
      env:
        VCPKG_ROOT: ${{ github.workspace }}/vcpkg
      run: |
        cmake -S . -B build -G "Ninja Multi-Config" `
          -DCMAKE_BUILD_TYPE=Release `
          -DCMAKE_PREFIX_PATH="${{ env.Qt5_Dir }}" `
          -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake" `
          -DVCPKG_TARGET_TRIPLET=x64-windows `
          -DCMAKE_VERBOSE_MAKEFILE=ON
          
    - name: Configure CMake (macOS)
      if: matrix.os == 'macos-latest'
      continue-on-error: true
      run: |
        cmake -S . -B build -G "Ninja Multi-Config" \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_PREFIX_PATH="${{ env.Qt5_Dir }}" \
          -DCMAKE_OSX_ARCHITECTURES=x86_64
          
    - name: Configure CMake (Linux)
      if: matrix.os == 'ubuntu-latest'
      continue-on-error: true
      run: |
        cmake -S . -B build -G "Ninja Multi-Config" \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_PREFIX_PATH="${{ env.Qt5_Dir }}"
          
    - name: Build
      continue-on-error: true
      run: cmake --build build --config Release
      
    - name: Package (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      continue-on-error: true
      run: |
        cd build
        cpack -G DEB -C Release
        cpack -G TGZ -C Release
        
    - name: Package (Windows)
      if: matrix.os == 'windows-latest'
      continue-on-error: true
      run: |
        cd build
        cpack -G NSIS -C Release
        
    - name: Package (macOS)
      if: matrix.os == 'macos-latest'
      continue-on-error: true
      run: |
        cd build
        cpack -G DragNDrop -C Release
        
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      continue-on-error: true
      with:
        name: cfping-windows-latest
        path: |
          build/*.exe
          build/_CPack_Packages/*/NSIS/*.exe
        retention-days: 30
      if: matrix.os == 'windows-latest'
        
    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v4
      continue-on-error: true
      with:
        name: cfping-ubuntu-latest
        path: |
          build/*.deb
          build/*.tar.gz
        retention-days: 30
      if: matrix.os == 'ubuntu-latest'
        
    - name: Upload macOS artifacts
      uses: actions/upload-artifact@v4
      continue-on-error: true
      with:
        name: cfping-macos-latest
        path: build/*.dmg
        retention-days: 30
      if: matrix.os == 'macos-latest'
